### ISSUE TITLE
Fancybox 3 installation issue

### ISSUE THREAD

**Issue by bhumiradixweb** [olsonpm/fancybox#4]
Hello,

`npm install fancybox --save-dev`

This command is not installing version 3. It is installing  version: 2.1.5. How to install latest?

**Comment by olsonpm** [comment]
Seems you're looking for [the package @fancyapps/fancybox](https://www.npmjs.com/package/@fancyapps/fancybox)



[This thread](https://github.com/olsonpm/fancybox/issues/3) explains why I have the vanilla fancybox npm package.  I hope you understand.

**Comment by bhumiradixweb** [comment]
What is the difference between @fancyapps and fancybox i have installed?

**Comment by olsonpm** [comment]
This is a fork of the [original fancybox repo](https://github.com/fancyapps/fancybox) that I made a few years ago.  When you install my fancybox from npm, you're installing version 3 of my repo which is version 2.1.5 of the original.  If you install @fancyapps/fancybox from npm then you will get version 3.1.25 of the original repo.

I tried to make this clear [in my README](https://www.npmjs.com/package/fancybox).  If you have suggestions on how I can make this more clear then let me know.

**Comment by olsonpm** [comment]
I created this fork because, at the time, fancybox didn't exist on npm.  The original repo also wasn't very bundler-friendly (e.g. browserify) so I made some changes to make it work better via npm.

I will add that to the readme.  It didn't make sense to put that on the readme 2 years ago because the version was up to date.

**Comment by chpio** [comment]
> The original repo also wasn't very bundler-friendly (e.g. browserify) so I made some changes to make it work better via npm.

It is *still* [broken](https://github.com/fancyapps/fancybox/issues/1371#issuecomment-294119331). And they do not want to change that fact.

**Comment by chpio** [comment]
is there a possibility to release `fancybox@4` that is actually just an unborked original fancybox v3?

**Comment by olsonpm** [comment]
i haven't used fancybox in some time, but i'm open to a PR
